In [1]:
import numpy as np

# 使用 arange() 创建从 1 到 12 的一维数组
arr = np.arange(1, 13)
# 使用 reshape() 重塑为 3行4列的二维数组
arr_reshaped = arr.reshape(3, 4)

print("数组内容:")
print(arr_reshaped)
print("维度 (ndim):", arr_reshaped.ndim)
print("形状 (shape):", arr_reshaped.shape)
print("元素总个数 (size):", arr_reshaped.size)

数组内容:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
维度 (ndim): 2
形状 (shape): (3, 4)
元素总个数 (size): 12


In [2]:
import numpy as np

# 创建包含浮点数的数组
float_arr = np.array([1.5, 2.6, 3.7, 4.8])

print("转换前的数组:", float_arr)
print("转换前的数据类型:", float_arr.dtype.name)

# 使用 astype() 转换为 32位整数
int_arr = float_arr.astype(np.int32)

print("转换后的数组:", int_arr)
print("转换后的数据类型:", int_arr.dtype.name)

转换前的数组: [1.5 2.6 3.7 4.8]
转换前的数据类型: float64
转换后的数组: [1 2 3 4]
转换后的数据类型: int32


In [3]:
import numpy as np

# 创建二维数组
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 获取前两行，第2到第3列（索引1:3，不包含索引3）
sub_arr = arr[1:3, 0:4]  # 或者 arr[:2, 1:3]

print("原数组:")
print(arr)
print("\n切片结果:")
print(sub_arr)

原数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

切片结果:
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
import numpy as np

arr = np.array([10, 15, 20, 25, 30, 35])

fancy_indexed = arr[[0, 2, 4]]
print("花式索引结果:", fancy_indexed)

bool_indexed = arr[arr%2==0]
print("布尔索引结果:", bool_indexed)

花式索引结果: [10 20 30]
布尔索引结果: [10 20 30]


In [5]:
import numpy as np

# 创建形状为(3, 4)的全0数组
zeros_arr = np.zeros((3, 4))
# 创建一维数组
arr_b = np.array([1, 2, 3, 4])

# 利用广播机制相加
result = zeros_arr + arr_b

print("全0数组:")
print(zeros_arr)
print("\n一维数组 arr_b:", arr_b)
print("\n相加结果:")
print(result)

全0数组:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

一维数组 arr_b: [1 2 3 4]

相加结果:
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [6]:
import numpy as np

# 给定数组
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])

# 1. 使用np.sqrt()计算x的平方根
sqrt_x = np.sqrt(x)
print("x的平方根:", sqrt_x)

# 2. 使用np.maximum()找出对应位置上的最大值
max_result = np.maximum(sqrt_x, y)
print("对应位置最大值:", max_result)

x的平方根: [1. 2. 3. 4.]
对应位置最大值: [2. 2. 4. 5.]


In [7]:
import numpy as np

# 创建形状为(2, 3, 4)的三维数组
arr = np.arange(24).reshape((2, 3, 4))

print("原数组形状:", arr.shape)

# 使用transpose()转换轴顺序为(1, 0, 2)
transposed_arr = arr.transpose(1, 0, 2)

print("转置后数组形状:", transposed_arr.shape)

原数组形状: (2, 3, 4)
转置后数组形状: (3, 2, 4)


In [8]:
import numpy as np

# 给定数组
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])

# 使用np.where()进行条件选择
result = np.where(arr_con, arr_x, arr_y)

print("arr_x:", arr_x)
print("arr_y:", arr_y)
print("条件数组 arr_con:", arr_con)
print("np.where()结果:", result)

arr_x: [1 5 7]
arr_y: [2 6 8]
条件数组 arr_con: [ True False  True]
np.where()结果: [1 6 7]


In [9]:
import numpy as np

# 创建二维数组
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])

print("原数组:")
print(arr)

# 1. 计算所有元素的算术平均值
mean_value = arr.mean()
print("\n所有元素的平均值:", mean_value)

# 2. 沿着axis=0方向（按列）排序
sorted_arr = np.sort(arr, axis=0)
print("\n按列排序后的数组:")
print(sorted_arr)

原数组:
[[6 2 7]
 [3 6 2]
 [4 3 2]]

所有元素的平均值: 3.888888888888889

按列排序后的数组:
[[3 2 2]
 [4 3 2]
 [6 6 7]]


In [10]:
import numpy as np

# 设置随机数种子
np.random.seed(10)

# 1. 生成两个(2, 2)的随机矩阵
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

print("矩阵A:")
print(A)
print("\n矩阵B:")
print(B)

# 2. 计算矩阵A和B的点积
dot_product = np.dot(A, B)

print("\n矩阵点积 A·B:")
print(dot_product)

矩阵A:
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]

矩阵B:
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]

矩阵点积 A·B:
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
